### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by metalgalz** [rahadiana/php-spell-checker#1]
![123](https://user-images.githubusercontent.com/42573802/144730551-a9f5a91b-1168-4ed4-88c2-6ecc40e62fa3.png)

Tolong di perbaiki

**Comment by rahadiana** [comment]
terimakasih atas partisipasinya, kode yang broken sudah di perbaiki [#647b65e](https://github.com/rahadiana/php-spell-checker/commit/647b65e896e108eb4b568bb95e8cab9827af2f4b)

**Comment by stevennarru** [comment]
saya barusan sempat coba tadi bisa. namun ini hendak mencoba lagi setelah saya tinggal aktifitas, hasilnya sama seperti yang di screenshot metalgalz. 
![image](https://user-images.githubusercontent.com/51007698/145056483-4cdd45ca-315a-47a1-9b14-e10da623606b.png)
![image](https://user-images.githubusercontent.com/51007698/145056756-7528476a-73ac-4cc3-91f5-8739e4c49572.png)

**Comment by rahadiana** [comment]
network google membatasi aktifitas tidak wajar, mungkin IP / jaringan anda telah di tandai sebagai aktifitas tidak wajar.

**Comment by stevennarru** [comment]
oh, begitu ya. terima kasih, kak.
ini barusan saya coba lagi pakai koneksi internet yang berbeda sudah bisa.
terima kasih banyak kak Rahadiana :)
sukses selalu kak.

**Comment by metalgalz** [comment]
Gak isok pantek
